/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import javax.swing.JOptionPane;

/**
 *
 * @author s.lucas
 */
public class Horoscopoprincipal extends javax.swing.JFrame {

    /**
     * Creates new form Horoscopoprincipal
     */
    public Horoscopoprincipal() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbFeminino = new javax.swing.JRadioButton();
        rbMasculino = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cbDia = new javax.swing.JComboBox<>();
        cbMes = new javax.swing.JComboBox<>();
        cbAno = new javax.swing.JComboBox<>();
        btMostrarSigno = new javax.swing.JButton();
        btMostrarEstacao = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GURU DO DESKTOP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 414, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("NOME:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 51, 414, 15);

        edNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNomeActionPerformed(evt);
            }
        });
        getContentPane().add(edNome);
        edNome.setBounds(10, 72, 414, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("SEXO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 113, 35, 15);

        grupoSexo.add(rbFeminino);
        rbFeminino.setSelected(true);
        rbFeminino.setText("Feminino");
        getContentPane().add(rbFeminino);
        rbFeminino.setBounds(63, 110, 67, 23);

        grupoSexo.add(rbMasculino);
        rbMasculino.setText("Masculino");
        getContentPane().add(rbMasculino);
        rbMasculino.setBounds(148, 110, 71, 23);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("DATA DE NASCIMENTO:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 151, 131, 15);

        cbDia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o dia...", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cbDia);
        cbDia.setBounds(10, 184, 121, 23);

        cbMes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o mês...", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(cbMes);
        cbMes.setBounds(149, 184, 132, 23);

        cbAno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o ano...", "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037" }));
        getContentPane().add(cbAno);
        cbAno.setBounds(299, 184, 125, 23);

        btMostrarSigno.setText("MOSTRAR SIGNO");
        btMostrarSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarSignoActionPerformed(evt);
            }
        });
        getContentPane().add(btMostrarSigno);
        btMostrarSigno.setBounds(10, 225, 209, 23);

        btMostrarEstacao.setText("MOSTRAR A ESTAÇÃO DO ANO");
        btMostrarEstacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarEstacaoActionPerformed(evt);
            }
        });
        getContentPane().add(btMostrarEstacao);
        btMostrarEstacao.setBounds(237, 225, 187, 23);

        btLimpar.setText("LIMPAR");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(10, 266, 414, 23);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(270, 100, 100, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja limpar os campos?", "Confirme",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            edNome.setText(null);
            rbFeminino.setSelected(true);
            cbDia.setSelectedIndex(0);
            cbMes.setSelectedIndex(0);
            cbAno.setSelectedIndex(0);
            edNome.requestFocus();
            JOptionPane.showMessageDialog(null, "Os campos foram limpos!");
            
        } else {
            JOptionPane.showMessageDialog(null, "Limpeza cancelada!"); 
        }
    }//GEN-LAST:event_btLimparActionPerformed

    private void btMostrarSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarSignoActionPerformed
        String nome, sexo;
        int dia, mes, ano;
        nome = edNome.getText();
        dia = Integer.parseInt((String) cbDia.getModel().getSelectedItem());
        mes = Integer.parseInt((String) cbMes.getModel().getSelectedItem());
        if (rbFeminino.isSelected()) {
            sexo = "Sra.";
        } else {
            sexo = "Sr.";
        }
        if (dia >= 21 && dia <= 31 && mes == 3 || dia >= 1 && dia <= 20 && mes == 4) {
            JOptionPane.showMessageDialog(null, sexo + " " + nome + " seu signo é áries");
        } else if (dia >= 21 && dia <= 30 && mes == 4 || dia >= 1 && dia <= 20 && mes == 5) {
            JOptionPane.showMessageDialog(null, sexo + " " + nome + " seu signo é touro");
        } else if (dia >= 21 && dia <= 31 && mes == 5 || dia >= 1 && dia <= 20 && mes == 6) {
            JOptionPane.showMessageDialog(null, sexo + " " + nome + " seu signo é gêmeos");
        } else if (dia >= 21 && dia <= 30 && mes == 6 || dia >= 1 && dia <= 22 && mes == 7) {
            JOptionPane.showMessageDialog(null, sexo + " " + nome + " seu signo é câncer");
        } else if (dia >= 23 && dia <= 31 && mes == 7 || dia >= 1 && dia <= 22 && mes == 8) {
            JOptionPane.showMessageDialog(null, sexo + " " + nome + " seu signo é leão");
        } else if (dia >= 23 && dia <= 31 && mes == 8 || dia >= 1 && dia <= 22 && mes == 9) {
            JOptionPane.showMessageDialog(null, sexo + " " + nome + " seu signo é virgem");
        } else if (dia >= 23 && dia <= 30 && mes == 9 || dia >= 1 && dia <= 22 && mes == 10) {
            JOptionPane.showMessageDialog(null, sexo + " " + nome + " seu signo é libra");
        } else if (dia >= 23 && dia <= 31 && mes == 10 || dia >= 1 && dia <= 21 && mes == 11) {
            JOptionPane.showMessageDialog(null, sexo + " " + nome + " seu signo é escorpião");
        } else if (dia >= 22 && dia <= 30 && mes == 11 || dia >= 1 && dia <= 21 && mes == 12) {
            JOptionPane.showMessageDialog(null, sexo + " " + nome + " seu signo é sagitário");
        } else if (dia >= 22 && dia <= 31 && mes == 12 || dia >= 1 && dia <= 20 && mes == 1) {
            JOptionPane.showMessageDialog(null, sexo + " " + nome + " seu signo é capricórnio");
        } else if (dia >= 21 && dia <= 31 && mes == 1 || dia >= 1 && dia <= 18 && mes == 2) {
            JOptionPane.showMessageDialog(null, sexo + " " + nome + " seu signo é aquário");
        } else if (dia >= 19 && dia <= 28 && mes == 2 || dia >= 1 && dia <= 20 && mes == 3) {
            JOptionPane.showMessageDialog(null, sexo + " " + nome + " seu signo é peixes");
        }
    }//GEN-LAST:event_btMostrarSignoActionPerformed

    private void btMostrarEstacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarEstacaoActionPerformed
        String nome, sexo;
        int dia, mes, ano;
        nome = edNome.getText();
        dia = Integer.parseInt((String) cbDia.getModel().getSelectedItem());
        mes = Integer.parseInt((String) cbMes.getModel().getSelectedItem());
        if (rbFeminino.isSelected()) {
            sexo = "Sra.";
        } else {
            sexo = "Sr.";
        }
        if (dia >= 20 && dia <= 31 && mes == 3 || dia >= 1 && dia <= 31 && mes == 4
                || dia >= 1 && dia <= 31 && mes == 5 || dia >= 1 && dia <= 21 && mes == 6) {
            JOptionPane.showMessageDialog(null, sexo + " " + nome + " você nasceu no outono");
        } else if (dia >= 22 && dia <= 31 && mes == 6 || dia >= 1 && dia <= 31 && mes == 7
                || dia >= 1 && dia <= 31 && mes == 8 || dia >= 1 && dia <= 22 && mes == 9) {
            JOptionPane.showMessageDialog(null, sexo + " " + nome + " você nasceu no inverno");
        } else if (dia >= 23 && dia <= 31 && mes == 9 || dia >= 1 && dia <= 31 && mes == 10
                || dia >= 1 && dia <= 31 && mes == 11 || dia >= 1 && dia <= 21 && mes == 12) {
            JOptionPane.showMessageDialog(null, sexo + " " + nome + " você naceu na primavera");
        } else if (dia >= 22 && dia <= 31 && mes == 12 || dia >= 1 && dia <= 31 && mes == 1
                || dia >= 1 && dia <= 31 && mes == 2 || dia >= 1 && dia <= 19 && mes == 3) {
            JOptionPane.showMessageDialog(null, sexo + " " + nome + " você nasceu no verão");
        }
    }//GEN-LAST:event_btMostrarEstacaoActionPerformed

    private void edNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Horoscopoprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Horoscopoprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Horoscopoprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Horoscopoprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Horoscopoprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btMostrarEstacao;
    private javax.swing.JButton btMostrarSigno;
    private javax.swing.JComboBox<String> cbAno;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JTextField edNome;
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.JRadioButton rbMasculino;
    // End of variables declaration//GEN-END:variables

}
